export const FACTORY_ABI = [
  // Read functions
  "function owner() view returns (address)",
  "function totalMarkets() view returns (uint256)",
  "function markets(uint256) view returns (address)",
  "function isMarket(address) view returns (bool)",
  "function minBWad() view returns (int256)",
  "function maxBWad() view returns (int256)",
  "function minDuration() view returns (uint256)",
  "function maxDuration() view returns (uint256)",
  "function getMarkets(uint256 offset, uint256 limit) view returns (address[])",
  "function getMarketCount() view returns (uint256)",

  // Write functions
  "function createMarket(string _title, string _description, string _category, string _imageUri, string[] _outcomeLabels, int256 _bWad, uint256 _durationSeconds) returns (address market)",
  "function setMinBWad(int256 _min)",
  "function setMaxBWad(int256 _max)",
  "function setDurationBounds(uint256 _min, uint256 _max)",
  "function editMarket(address market, string _title, string _description, string _category)",

  // Events
  "event MarketCreated(address indexed market, uint256 indexed marketId, address indexed creator, string title, string category, uint256 outcomeCount, uint256 deadline)",
] as const;

export const LENS_ABI = [
  // Global stats
  "function getGlobalStats() view returns (tuple(uint256 totalMarkets, uint256 totalVolumeWei, uint256 totalParticipants, uint256 activeMarkets, uint256 resolvedMarkets, uint256 cancelledOrExpiredMarkets))",

  // Paginated market list
  "function getMarketSummaries(uint256 offset, uint256 limit) view returns (tuple(address market, uint256 marketId, string title, string category, string imageUri, string[] outcomeLabels, int256[] impliedProbabilitiesWad, uint8 stage, uint256 winningOutcome, uint256 marketDeadline, uint256 totalVolumeWei, uint256 participants, int256 bWad)[])",

  // Single market detail (includes resolvedPoolWei + resolutionDeadline + cancel info)
  "function getMarketDetail(address market) view returns (tuple(address market, string title, string description, string category, string imageUri, string proofUri, string[] outcomeLabels, int256[] totalSharesWad, int256[] impliedProbabilitiesWad, uint8 stage, uint256 winningOutcome, uint256 createdAt, uint256 marketDeadline, int256 bWad, uint256 totalVolumeWei, uint256 participants, uint256 resolvedPoolWei, uint256 resolutionDeadline, string cancelReason, string cancelProofUri))",

  // User portfolio
  "function getUserPortfolio(address user) view returns (tuple(address market, string title, string category, string[] outcomeLabels, uint256[] sharesPerOutcome, uint256 netDepositedWei, bool canRedeem, bool canRefund, bool hasRedeemed, bool hasRefunded, uint8 stage)[])",
] as const;

export const MARKET_ABI = [
  // Read functions
  "function title() view returns (string)",
  "function description() view returns (string)",
  "function category() view returns (string)",
  "function imageUri() view returns (string)",
  "function proofUri() view returns (string)",
  "function cancelReason() view returns (string)",
  "function cancelProofUri() view returns (string)",
  "function admin() view returns (address)",
  "function stage() view returns (uint8)",
  "function b() view returns (int256)",
  "function outcomeCount() view returns (uint256)",
  "function winningOutcome() view returns (uint256)",
  "function marketDeadline() view returns (uint256)",
  "function createdAt() view returns (uint256)",
  "function totalVolumeWei() view returns (uint256)",
  "function totalNetDepositedWei() view returns (uint256)",
  "function participantCount() view returns (uint256)",
  "function sharesOf(address, uint256) view returns (uint256)",
  "function netDepositedWei(address) view returns (uint256)",
  "function hasRedeemed(address) view returns (bool)",
  "function hasRefunded(address) view returns (bool)",
  "function resolvedPoolWei() view returns (uint256)",
  "function resolutionDeadline() view returns (uint256)",
  "function PLATFORM_FEE_BPS() view returns (uint256)",
  "function RESOLUTION_GRACE_PERIOD() view returns (uint256)",

  // View functions
  "function getMarketInfo() view returns (string _title, string _description, string _category, string _imageUri, string _proofUri, string[] _outcomeLabels, uint8 _stage, uint256 _winningOutcome, uint256 _createdAt, uint256 _marketDeadline, uint256 _totalVolumeWei, uint256 _participantCount, string _cancelReason, string _cancelProofUri)",
  "function getShares() view returns (int256[])",
  "function getImpliedProbabilities() view returns (int256[])",
  "function previewBuy(uint256 outcomeIdx, uint256 sharesWad) view returns (uint256 costWei)",
  "function previewSell(uint256 outcomeIdx, uint256 sharesWad) view returns (uint256 proceedsWei)",
  "function getUserInfo(address user) view returns (uint256[] _shares, uint256 _netDeposited, bool _redeemed, bool _refunded, bool _canRedeem, bool _canRefund)",

  // Write functions
  "function buy(uint256 outcomeIdx, uint256 sharesWad, uint256 maxCostWei) payable",
  "function sell(uint256 outcomeIdx, uint256 sharesWad, uint256 minReceiveWei)",
  "function resolve(uint256 _winningOutcome, string _proofUri)",
  "function cancel(string reason, string _proofUri)",
  "function editMarket(string _title, string _description, string _category)",
  "function suspend()",
  "function resume()",
  "function editDeadline(uint256 newDeadline)",
  "function triggerExpiry()",
  "function redeem()",
  "function refund()",

  // Events
  "event SharesBought(address indexed trader, uint256 indexed outcomeIndex, uint256 sharesWad, uint256 costWei)",
  "event SharesSold(address indexed trader, uint256 indexed outcomeIndex, uint256 sharesWad, uint256 proceedsWei)",
  "event MarketResolved(uint256 winningOutcome, string proofUri)",
  "event MarketCancelled(string reason, string proofUri)",
  "event MarketEdited(string newTitle, string newDescription, string newCategory)",
  "event Redeemed(address indexed user, uint256 amountWei)",
  "event Refunded(address indexed user, uint256 amountWei)",
  "event FeeCollected(address indexed recipient, uint256 amountWei)",
] as const;

export const MARKET_V2_ABI = [
  "function title() view returns (string)",
  "function description() view returns (string)",
  "function category() view returns (string)",
  "function imageUri() view returns (string)",
  "function stage() view returns (uint8)",
  "function outcomeCount() view returns (uint256)",
  "function marketDeadline() view returns (uint256)",
  "function resolutionTime() view returns (uint256)",
  "function resolutionSource() view returns (string)",
  "function fallbackResolutionSource() view returns (string)",
  "function invalidCondition() view returns (string)",
  "function resolutionManager() view returns (address)",
  "function sharesOf(address, uint256) view returns (uint256)",
  "function hasParticipated(address) view returns (bool)",
  "function isTradingOpen() view returns (bool)",
  "function getMarketInfo() view returns (string _title, string _description, string _category, string _imageUri, string _proofUri, string[] _outcomeLabels, uint8 _stage, uint256 _winningOutcome, uint256 _createdAt, uint256 _marketDeadline, uint256 _totalVolumeWei, uint256 _participantCount, string _cancelReason, string _cancelProofUri)",
  "function getShares() view returns (int256[])",
  "function getImpliedProbabilities() view returns (int256[])",
  "function getImpliedProbability(uint256 outcomeIdx) view returns (uint256)",
  "function getResolutionRules() view returns (string _resolutionSource, uint256 _resolutionTime, string _fallbackResolutionSource, string _invalidCondition, address _resolutionManager)",
  "function previewBuy(uint256 outcomeIdx, uint256 sharesWad) view returns (uint256)",
  "function previewSell(uint256 outcomeIdx, uint256 sharesWad) view returns (uint256)",
  "function redeem()",
  "function setAuthorizedOperator(address operator, bool allowed)",
  "function setResolutionManager(address _resolutionManager)",
  "function editResolutionRules(string _resolutionSource, uint256 _resolutionTime, string _fallbackResolutionSource, string _invalidCondition)",
  "function emergencyCancel(string reason, string _proofUri)",
  "event SharesBought(address indexed trader, uint256 indexed outcomeIndex, uint256 sharesWad, uint256 costWei)",
  "event SharesSold(address indexed trader, uint256 indexed outcomeIndex, uint256 sharesWad, uint256 proceedsWei)",
  "event SharesMoved(address indexed from, address indexed to, uint256 indexed outcomeIndex, uint256 sharesWad)",
  "event MarketInitialized(address indexed owner, address indexed resolutionManager, uint256 outcomeCount, int256 bWad, uint256 marketDeadline, uint256 resolutionTime)",
  "event OwnershipTransferred(address indexed previousOwner, address indexed newOwner)",
] as const;

export const MARKET_ROUTER_ABI = [
  "function orderBook() view returns (address)",
  "function feeRecipient() view returns (address)",
  "function orderBookTakerFeeBps() view returns (uint256)",
  "function lmsrTakerFeeBps() view returns (uint256)",
  "function MAX_HOPS_LIMIT() view returns (uint256)",
  "function MAX_FEE_BPS() view returns (uint256)",
  "function chunkSizeWad() view returns (uint256)",
  "function maxTradeSharesWad() view returns (uint256)",
  "function defaultMaxHops() view returns (uint256)",
  "function clobPaused() view returns (bool)",
  "function allowedMarket(address market) view returns (bool)",
  "function buy(address market, uint256 outcome, uint256 sharesWad, uint256 minSharesOutWad, uint256 maxCostWei, uint256 maxHops, uint256 deadline) payable returns (tuple(uint256 requestedSharesWad, uint256 filledSharesWad, uint256 orderBookSharesWad, uint256 lmsrSharesWad, uint256 costWei, uint256 proceedsWei, uint256 feeWei, bool usedOrderBook, bool usedLmsr, bool isPartial))",
  "function sell(address market, uint256 outcome, uint256 sharesWad, uint256 minProceedsWei, uint256 maxHops, uint256 deadline) returns (tuple(uint256 requestedSharesWad, uint256 filledSharesWad, uint256 orderBookSharesWad, uint256 lmsrSharesWad, uint256 costWei, uint256 proceedsWei, uint256 feeWei, bool usedOrderBook, bool usedLmsr, bool isPartial))",
  "function previewTrade(address market, uint256 outcome, uint8 side, uint256 sharesWad, uint256 maxHops) view returns (tuple(uint256 requestedSharesWad, uint256 filledSharesWad, uint256 orderBookSharesWad, uint256 lmsrSharesWad, uint256 costWei, uint256 proceedsWei, uint256 feeWei, bool usedOrderBook, bool usedLmsr, bool isPartial))",
  "function getBestExecution(address market, uint256 outcome, uint8 side, uint256 sharesWad, uint256 maxHops) view returns (tuple(uint256 requestedSharesWad, uint256 filledSharesWad, uint256 orderBookSharesWad, uint256 lmsrSharesWad, uint256 costWei, uint256 proceedsWei, uint256 feeWei, bool usedOrderBook, bool usedLmsr, bool isPartial))",
  "function setAllowedMarket(address market, bool allowed)",
  "function setClobPaused(bool paused)",
  "function setFees(uint256 _orderBookTakerFeeBps, uint256 _lmsrTakerFeeBps)",
  "function setExecutionConfig(uint256 _chunkSizeWad, uint256 _maxTradeSharesWad, uint256 _defaultMaxHops)",
  "event HybridTrade(address indexed trader, address indexed market, uint256 indexed outcome, uint8 side, uint256 requestedSharesWad, uint256 filledSharesWad, uint256 orderBookSharesWad, uint256 lmsrSharesWad, uint256 costWei, uint256 proceedsWei, uint256 feeWei)",
  "event OrderBookFallback(address indexed market, uint256 indexed outcome, uint8 side, uint256 remainingSharesWad)",
] as const;

export const ORDER_BOOK_ABI = [
  "function router() view returns (address)",
  "function feeRecipient() view returns (address)",
  "function tickSizeWad() view returns (uint256)",
  "function minOrderSharesWad() view returns (uint256)",
  "function maxPriceDeviationBps() view returns (uint256)",
  "function MAX_PRICE_LEVELS() view returns (uint256)",
  "function MAX_FEE_BPS() view returns (uint256)",
  "function makerFeeBps() view returns (uint256)",
  "function paused() view returns (bool)",
  "function allowedMarket(address market) view returns (bool)",
  "function orders(uint256 orderId) view returns (uint256 id, address market, uint256 outcome, address owner, uint8 side, uint256 priceWad, uint256 remainingSharesWad, uint256 escrowWei, uint256 expiry, bool active)",
  "function placeLimitOrder(address market, uint256 outcome, uint8 side, uint256 priceWad, uint256 sharesWad, uint256 expiry) payable returns (uint256 orderId)",
  "function cancelOrder(uint256 orderId)",
  "function pruneExpiredOrder(uint256 orderId)",
  "function getBestBid(address market, uint256 outcome) view returns (uint256 priceWad, uint256 sharesWad, uint256 orderId)",
  "function getBestAsk(address market, uint256 outcome) view returns (uint256 priceWad, uint256 sharesWad, uint256 orderId)",
  "function getDepth(address market, uint256 outcome, uint8 side, uint256 maxLevels) view returns (uint256[] pricesWad, uint256[] sharesWad)",
  "function previewFill(address market, uint256 outcome, uint8 side, uint256 maxSharesWad, uint256 limitPriceWad) view returns (uint256 sharesFilledWad, uint256 notionalWei)",
  "function setAllowedMarket(address market, bool allowed)",
  "function setPaused(bool _paused)",
  "function setMakerFeeBps(uint256 _makerFeeBps)",
  "function setOrderConstraints(uint256 _tickSizeWad, uint256 _minOrderSharesWad, uint256 _maxPriceDeviationBps)",
  "event OrderPlaced(uint256 indexed orderId, address indexed market, address indexed owner, uint256 outcome, uint8 side, uint256 priceWad, uint256 sharesWad, uint256 expiry)",
  "event OrderCancelled(uint256 indexed orderId, address indexed owner, uint256 remainingSharesWad, uint256 refundWei)",
  "event OrderPruned(uint256 indexed orderId, address indexed market, uint256 indexed outcome, uint8 side, uint256 priceWad)",
  "event OrderFilled(uint256 indexed orderId, address indexed market, address indexed taker, uint256 outcome, uint8 side, uint256 sharesWad, uint256 notionalWei, uint256 makerFeeWei)",
] as const;

export const HYBRID_FACTORY_ABI = [
  "function owner() view returns (address)",
  "function totalMarkets() view returns (uint256)",
  "function markets(uint256) view returns (address)",
  "function isMarket(address) view returns (bool)",
  "function router() view returns (address)",
  "function orderBook() view returns (address)",
  "function defaultResolutionManager() view returns (address)",
  "function marketImplementation() view returns (address)",
  "function creationPaused() view returns (bool)",
  "function minBWad() view returns (int256)",
  "function maxBWad() view returns (int256)",
  "function minDuration() view returns (uint256)",
  "function maxDuration() view returns (uint256)",
  "function getMarketCount() view returns (uint256)",
  "function getMarkets(uint256 offset, uint256 limit) view returns (address[])",
  "function createMarket(string _title, string _description, string _category, string _imageUri, string[] _outcomeLabels, int256 _bWad, uint256 _durationSeconds, string _resolutionSource, uint256 _resolutionTime, string _fallbackResolutionSource, string _invalidCondition) payable returns (address market)",
  "function setMarketResolutionManager(address market, address resolutionManager)",
  "function setRouter(address _router)",
  "function setOrderBook(address _orderBook)",
  "function setDefaultResolutionManager(address _resolutionManager)",
  "function setMarketImplementation(address _marketImplementation)",
  "function setCreationPaused(bool paused)",
  "function setMarketOperator(address market, address operator, bool allowed)",
  "function setMarketAllowed(address market, bool allowed)",
  "function editMarket(address market, string _title, string _description, string _category)",
  "function editResolutionRules(address market, string _resolutionSource, uint256 _resolutionTime, string _fallbackResolutionSource, string _invalidCondition)",
  "function emergencyCancelMarket(address market, string reason, string proofUri)",
  "event MarketCreated(address indexed market, uint256 indexed marketId, address indexed creator, string title, string category, uint256 outcomeCount, uint256 deadline, uint256 resolutionTime, address resolutionManager)",
  "event CreationPausedUpdated(bool paused)",
] as const;

export const HYBRID_LENS_ABI = [
  "function getMarketSummaries(uint256 offset, uint256 limit) view returns (tuple(address market, uint256 marketId, string title, string category, string imageUri, string[] outcomeLabels, int256[] impliedProbabilitiesWad, uint8 stage, uint256 winningOutcome, uint256 marketDeadline, uint256 resolutionTime, uint256 totalVolumeWei, uint256 participants, int256 bWad)[])",
  "function getMarketDetail(address market) view returns (tuple(address market, string title, string description, string category, string imageUri, string proofUri, string[] outcomeLabels, int256[] totalSharesWad, int256[] impliedProbabilitiesWad, uint8 stage, uint256 winningOutcome, uint256 createdAt, uint256 marketDeadline, uint256 resolutionTime, int256 bWad, uint256 totalVolumeWei, uint256 participants, uint256 resolvedPoolWei, string cancelReason, string cancelProofUri, string resolutionSource, string fallbackResolutionSource, string invalidCondition, address resolutionManager))",
  "function getOrderBookSnapshot(address market) view returns (tuple(uint256[] bestBidPriceWad, uint256[] bestBidSharesWad, uint256[] bestBidOrderId, uint256[] bestAskPriceWad, uint256[] bestAskSharesWad, uint256[] bestAskOrderId))",
  "function getUserPortfolio(address user) view returns (tuple(address market, string title, string category, string[] outcomeLabels, uint256[] sharesPerOutcome, bool canRedeem, bool hasRedeemed, uint8 stage)[])",
  "function getUserPortfolioSlice(address user, uint256 offset, uint256 limit) view returns (tuple(address market, string title, string category, string[] outcomeLabels, uint256[] sharesPerOutcome, bool canRedeem, bool hasRedeemed, uint8 stage)[])",
] as const;

export const RESOLUTION_MANAGER_ABI = [
  "function challengeWindow() view returns (uint256)",
  "function minBondWei() view returns (uint256)",
  "function maxBondWei() view returns (uint256)",
  "function bondBps() view returns (uint256)",
  "function resolverRewardWei() view returns (uint256)",
  "function paused() view returns (bool)",
  "function allowedMarket(address market) view returns (bool)",
  "function marketPaused(address market) view returns (bool)",
  "function activeProposalForMarket(address market) view returns (uint256)",
  "function requiredBond(address market) view returns (uint256)",
  "function proposals(uint256 proposalId) view returns (uint256 id, address market, address resolver, uint256 outcome, string evidenceUri, string proofUri, string reason, uint256 bondWei, uint256 createdAt, uint256 challengeDeadline, bool challenged, address challenger, uint256 counterOutcome, string counterEvidenceUri, string counterReason, bool finalized)",
  "function reputation(address user) view returns (int256 score, uint256 resolverWins, uint256 resolverLosses, uint256 challengerWins, uint256 challengerLosses, uint256 votesCast)",
  "function proposeResolution(address market, uint256 outcome, string evidenceUri, string proofUri, string reason) payable returns (uint256 proposalId)",
  "function challengeResolution(uint256 proposalId, uint256 counterOutcome, string counterEvidenceUri, string counterReason) payable",
  "function finalizeUnchallenged(uint256 proposalId)",
  "function resolveChallenge(uint256 proposalId, uint8 ruling)",
  "function voidProposal(uint256 proposalId, string reason)",
  "function emergencyCancelMarket(address market, string reason, string proofUri)",
  "function voteReputation(uint256 proposalId, bool supportsResolver, string reason)",
  "function setMarketAllowed(address market, bool allowed)",
  "function setPaused(bool _paused)",
  "function setMarketPaused(address market, bool _paused)",
  "function setBondConfig(uint256 _minBondWei, uint256 _maxBondWei, uint256 _bondBps, uint256 _resolverRewardWei)",
  "function setChallengeWindow(uint256 _challengeWindow)",
  "event ResolutionProposed(uint256 indexed proposalId, address indexed market, address indexed resolver, uint256 outcome, uint256 bondWei, uint256 challengeDeadline)",
  "event ResolutionChallenged(uint256 indexed proposalId, address indexed challenger, uint256 counterOutcome, uint256 bondWei)",
  "event ProposalFinalized(uint256 indexed proposalId, uint8 ruling, uint256 winningOutcome)",
  "event ProposalVoided(uint256 indexed proposalId, string reason)",
  "event ReputationVoted(uint256 indexed proposalId, address indexed voter, bool supportsResolver, string reason)",
] as const;
